# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "A top-down / API-first description language for modeling and generating cloud-native applications"
  homepage "https://github.com/apexlang/cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apexlang/cli/releases/download/v0.1.1/apex_darwin_amd64.tar.gz"
      sha256 "9f898f02e2bc00b0211312a5ddbcebced15d4da0073592ca9667248e7b554292"

      def install
        bin.install "apex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apexlang/cli/releases/download/v0.1.1/apex_darwin_arm64.tar.gz"
      sha256 "90e64d6ad90d9e6b6e3dd26495f01dfdf3df76af30d441ea77c0b7ea2be829a7"

      def install
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/apexlang/cli/releases/download/v0.1.1/apex_linux_amd64.tar.gz"
      sha256 "0e422162f52a98406da7c86f1bc5897a991f78721d146148bbff40680737e709"

      def install
        bin.install "apex"
      end
    end
  end
end
