# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apex < Formula
  desc "A top-down / API-first description language for modeling and generating cloud-native applications"
  homepage "https://github.com/apexlang/cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/apexlang/cli/releases/download/v0.1.2/apex_darwin_arm64.tar.gz"
      sha256 "3a8ddff19c355af3d1aa568fd1a0dcea5d216365c16da3e7e220e07ab543e5dc"

      def install
        bin.install "apex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/apexlang/cli/releases/download/v0.1.2/apex_darwin_amd64.tar.gz"
      sha256 "446b878b65c97c255bac66d0db0c4f2a0e2df40976242f4072b0910cb683284a"

      def install
        bin.install "apex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/apexlang/cli/releases/download/v0.1.2/apex_linux_amd64.tar.gz"
      sha256 "078facc10f361199adb7bfb968bf24f3a1bbbaf7830b380d9ddae96ec7490c3d"

      def install
        bin.install "apex"
      end
    end
  end
end
